// Svadharma Quiz — Seeker, Warrior, Builder, Server
window.QUIZ_DATA = {
  id: 'svadharma',
  meta: {
    en: {
      title: 'What Is Your<br><span style="color: var(--bo-gold-deep); font-weight: 500;">Svadharma Nature?</span>',
      shareTitle: 'Svadharma Nature',
      chapter: 'Bhagavad Gita · Chapter 18 · The Four Natures',
      intro: 'The Gita teaches that each person is born with a natural orientation — a svabhava, an innate quality — that shapes their dharma. BG 18.41–44 describes four essential types. This is not birth-caste but nature-type. This inquiry reveals yours.',
      tagPrefix: 'SVADHARMA · NATURE',
      categoryNames: { seeker: 'Seeker · Teacher', warrior: 'Warrior · Leader', builder: 'Builder · Creator', server: 'Server · Nurturer' }
    },
    hi: {
      title: 'आपकी<br><span style="color: var(--bo-gold-deep); font-weight: 500;">स्वधर्म प्रकृति क्या है?</span>',
      shareTitle: 'स्वधर्म प्रकृति',
      chapter: 'भगवद्गीता · अध्याय १८ · चार प्रकृतियां',
      intro: 'गीता सिखाती है कि प्रत्येक व्यक्ति एक स्वाभाविक अभिविन्यास के साथ जन्मता है — एक स्वभाव। BG १८.४१-४४ चार आवश्यक प्रकार बताता है। यह जन्म जाति नहीं, प्रकृति-प्रकार है। यह जिज्ञासा आपका प्रकट करती है।',
      tagPrefix: 'स्वधर्म · प्रकृति',
      categoryNames: { seeker: 'साधक · शिक्षक', warrior: 'योद्धा · नेता', builder: 'निर्माता · सृजनकर्ता', server: 'सेवक · पोषक' }
    }
  },
  categories: ['seeker', 'warrior', 'builder', 'server'],
  questions: {
    en: [
      { text: "What energizes you most in work?", tags: ["seeker","warrior","builder","server"], options: ["Understanding — inquiry, study, teaching, making meaning of things", "Challenge — leading, protecting, driving toward difficult goals under pressure", "Creating — building systems, ventures, abundance, things that last", "Serving — supporting others, giving care, being genuinely indispensable"] },
      { text: "What do you feel most called to offer the world?", tags: ["seeker","warrior","builder","server"], options: ["Clarity — illuminating what is true for those who are lost in confusion", "Protection — standing up for what is right, even when it costs something", "Prosperity — generating abundance and creating conditions for others to thrive", "Care — making lives easier, more dignified, or less painful"] },
      { text: "When a group faces a complex problem, you naturally:", tags: ["seeker","warrior","builder","server"], options: ["Research, reflect, and offer insight — you want to understand first", "Take charge, make a call, and drive toward resolution — someone has to move", "Find the practical solution — what resources do we have, what can work?", "Make sure everyone is supported and nothing falls through the cracks"] },
      { text: "What feels most like a violation of your deepest nature?", tags: ["seeker","warrior","builder","server"], options: ["Being forced to act without understanding — to do before you know why", "Being made passive when action is clearly needed — held back from the fight", "Waste — watching resources, time, or energy squandered without purpose", "Indifference — being told that the needs of people in front of you do not matter"] },
      { text: "Your natural relationship to authority is:", tags: ["seeker","warrior","builder","server"], options: ["You defer to truth, not rank — credentials matter less than actual insight", "You command it naturally — or you challenge it directly when it is wrong", "You work with it — authority is a tool, and you use whatever works", "You support it with loyalty — you find meaning in dedicated service to something greater"] },
      { text: "What gives you your deepest sense of satisfaction?", tags: ["seeker","warrior","builder","server"], options: ["The moment understanding breaks through — the insight that changes everything", "Victory — a hard goal achieved, a difficult challenge overcome with full effort", "A thriving creation — something built that works, sustains, and generates", "Knowing you made a genuine difference for a specific person who needed you"] },
      { text: "In a crisis, your first instinct is:", tags: ["seeker","warrior","builder","server"], options: ["Understand before acting — what is really happening beneath the surface?", "Move — take control of what can be controlled right now", "Solve practically — inventory resources, options, realistic paths forward", "Check on people first — who is hurting, who needs immediate help?"] },
      { text: "How do others most often describe you?", tags: ["seeker","warrior","builder","server"], options: ["Thoughtful, principled, perceptive, learned — someone with real depth", "Decisive, courageous, strong, direct — someone who moves when others hesitate", "Resourceful, industrious, practical — someone who always finds a way", "Reliable, caring, humble, indispensable — someone others count on"] },
      { text: "What is your relationship to knowledge?", tags: ["seeker","warrior","builder","server"], options: ["Sacred — I pursue it for its own sake, because truth matters intrinsically", "Instrumental — knowledge is power to act; I want the edge it gives", "Practical — I want the knowledge that makes what I am building actually work", "Relational — I want to know what helps the specific person in front of me"] },
      { text: "What has been your most consistent mode of contribution across your life?", tags: ["seeker","warrior","builder","server"], options: ["Teaching, guiding, writing, researching, making meaning", "Leading, protecting, competing, fighting for what is right", "Building — businesses, organizations, systems, wealth, structures that endure", "Serving — as caregiver, helper, supporter, the one who holds things together"] },
      { text: "What unsettles you most deeply when you see it in the world?", tags: ["seeker","warrior","builder","server"], options: ["Ignorance — people causing harm because they do not understand what they are doing", "Injustice — the powerful abusing those who cannot protect themselves", "Waste and poverty — resources mismanaged while genuine need goes unmet", "Neglect — those who need care being abandoned or made invisible"] },
      { text: "What discipline comes most naturally to you?", tags: ["seeker","warrior","builder","server"], options: ["Austerity of mind — sustained study, silence, self-restraint of thought", "Austerity of body — physical training, endurance, pushing past comfort", "Austerity of effort — consistent work, disciplined resource management", "Austerity of service — placing others first, sustained care as practice"] },
      { text: "What is your natural stance in a community or organization?", tags: ["seeker","warrior","builder","server"], options: ["The one who holds the vision and asks the questions no one else asks", "The one who steps forward to lead when leadership is genuinely needed", "The one who creates the conditions that allow everyone else to thrive", "The one who holds the community together through quiet, constant care"] },
      { text: "What does the Gita's concept of dharma mean to you personally?", tags: ["seeker","warrior","builder","server"], options: ["My duty is to seek, understand, and transmit truth honestly", "My duty is to stand for what is right and protect those who cannot protect themselves", "My duty is to create, sustain, and generate prosperity for the whole", "My duty is to serve those who need me — that is where I am most alive"] },
      { text: "If you had to teach one thing — one essential gift to the next generation — what would it be?", tags: ["seeker","warrior","builder","server"], options: ["How to think — how to inquire, discern, and see through appearances to truth", "How to be strong — courage, discipline, the willingness to stand and act", "How to build — systems, wealth, and the conditions for flourishing", "How to care — for others, for community, for life itself"] }
    ],
    hi: [
      { text: "काम में सबसे अधिक ऊर्जा क्या देता है?", tags: ["seeker","warrior","builder","server"], options: ["समझना — जिज्ञासा, अध्ययन, पढ़ाना, अर्थ बनाना", "चुनौती — नेतृत्व, रक्षा, कठिन लक्ष्यों की ओर", "सृजन — प्रणालियां, उद्यम, जो टिकता है बनाना", "सेवा — दूसरों को सहारा देना, देखभाल करना"] },
      { text: "आप संसार को सबसे अधिक क्या अर्पित करने के लिए बुलाए गए हैं?", tags: ["seeker","warrior","builder","server"], options: ["स्पष्टता — सत्य को प्रकाशित करना", "सुरक्षा — जो सही है उसके लिए खड़े होना", "समृद्धि — अवसर और प्रचुरता उत्पन्न करना", "देखभाल — जीवन आसान और सम्मानजनक बनाना"] },
      { text: "जटिल समस्या में समूह स्वाभाविक रूप से क्या करता है?", tags: ["seeker","warrior","builder","server"], options: ["शोध, चिंतन और अंतर्दृष्टि देना — पहले समझना", "नेतृत्व लेना, निर्णय लेना, आगे बढ़ना", "व्यावहारिक समाधान — संसाधन क्या हैं, क्या काम करेगा", "सुनिश्चित करना कि सबको सहारा मिले"] },
      { text: "क्या आपकी गहरी प्रकृति का उल्लंघन सा लगता है?", tags: ["seeker","warrior","builder","server"], options: ["बिना समझे कार्य करने पर मजबूर होना", "जब कार्रवाई ज़रूरी हो पर निष्क्रिय रहना पड़े", "बर्बादी — संसाधनों का दुरुपयोग", "उदासीनता — सामने वाले की ज़रूरत को अनदेखा करना"] },
      { text: "प्राधिकार से आपका स्वाभाविक संबंध?", tags: ["seeker","warrior","builder","server"], options: ["सत्य को मानता हूं, पद को नहीं", "स्वाभाविक रूप से कमान करता हूं या सीधे चुनौती देता हूं", "उपकरण के रूप में उपयोग करता हूं — जो काम करे", "वफादारी से समर्थन — समर्पित सेवा में अर्थ मिलता है"] },
      { text: "सबसे गहरी संतुष्टि कब मिलती है?", tags: ["seeker","warrior","builder","server"], options: ["जब समझ अचानक आती है — वह अंतर्दृष्टि जो सब बदल दे", "जीत — कठिन लक्ष्य पूरा होने पर", "एक फलती-फूलती रचना जो टिकती और उत्पन्न करती है", "यह जानकर कि किसी ज़रूरतमंद के लिए वास्तविक अंतर बनाया"] },
      { text: "संकट में पहली प्रवृत्ति?", tags: ["seeker","warrior","builder","server"], options: ["पहले समझो — सतह के नीचे क्या है?", "आगे बढ़ो — जो नियंत्रित किया जा सकता है वह करो", "व्यावहारिक रूप से हल करो — संसाधन, विकल्प", "लोगों पर ध्यान दो — कौन दर्द में है, किसे मदद चाहिए"] },
      { text: "दूसरे आपको सबसे अधिक कैसे वर्णित करते हैं?", tags: ["seeker","warrior","builder","server"], options: ["विचारशील, सैद्धांतिक, गहन — वास्तविक गहराई वाले", "निर्णायक, साहसी, प्रत्यक्ष — जहां दूसरे हिचकिचाएं", "साधन-संपन्न, परिश्रमी, व्यावहारिक — रास्ता निकालने वाले", "विश्वसनीय, देखभाल करने वाले, विनम्र, अपरिहार्य"] },
      { text: "ज्ञान से आपका संबंध?", tags: ["seeker","warrior","builder","server"], options: ["पवित्र — अपने लिए खोजता हूं, सत्य स्वयं में महत्वपूर्ण है", "उपकरण — ज्ञान शक्ति है, बढ़त देता है", "व्यावहारिक — जो काम आए वह चाहिए", "संबंधात्मक — सामने वाले की मदद करे वह जानना है"] },
      { text: "जीवन भर में सबसे सुसंगत योगदान क्या रहा?", tags: ["seeker","warrior","builder","server"], options: ["पढ़ाना, मार्गदर्शन, लेखन, शोध, अर्थ बनाना", "नेतृत्व, रक्षा, प्रतिस्पर्धा, सही के लिए संघर्ष", "निर्माण — व्यवसाय, संगठन, संरचनाएं", "सेवा — देखभाल करने वाले, सहारा देने वाले"] },
      { text: "संसार में क्या देखकर सबसे अधिक विचलित होते हैं?", tags: ["seeker","warrior","builder","server"], options: ["अज्ञान — बिना समझे नुकसान करना", "अन्याय — शक्तिशाली द्वारा कमज़ोर का शोषण", "बर्बादी और गरीबी — संसाधनों का दुरुपयोग", "उपेक्षा — ज़रूरतमंदों को अकेला छोड़ना"] },
      { text: "कौन सा अनुशासन सबसे स्वाभाविक है?", tags: ["seeker","warrior","builder","server"], options: ["मन का तप — निरंतर अध्ययन, मौन, विचार संयम", "शरीर का तप — शारीरिक प्रशिक्षण, सहनशक्ति", "प्रयास का तप — सुसंगत कार्य, संसाधन प्रबंधन", "सेवा का तप — दूसरों को पहले रखना, निरंतर देखभाल"] },
      { text: "समुदाय में आपकी स्वाभाविक भूमिका?", tags: ["seeker","warrior","builder","server"], options: ["जो दृष्टि रखे और वे प्रश्न पूछे जो और नहीं पूछते", "जो आगे आए जब नेतृत्व वास्तव में चाहिए", "जो सबके फलने-फूलने की स्थितियां बनाए", "जो शांत, निरंतर देखभाल से समुदाय को थामे"] },
      { text: "गीता का धर्म आपके लिए व्यक्तिगत रूप से क्या अर्थ रखता है?", tags: ["seeker","warrior","builder","server"], options: ["सत्य खोजना, समझना और ईमानदारी से देना मेरा कर्तव्य है", "जो सही है उसके लिए खड़े होना और रक्षा करना", "सृजन, पोषण और समृद्धि उत्पन्न करना", "उन्हें सेवा देना जिन्हें ज़रूरत है — वहीं मैं जीवित हूं"] },
      { text: "अगली पीढ़ी को एक सबसे ज़रूरी उपहार क्या देंगे?", tags: ["seeker","warrior","builder","server"], options: ["सोचना — जिज्ञासा, विवेक और सत्य देखना", "मज़बूत होना — साहस, अनुशासन, खड़े होने की इच्छा", "बनाना — संरचनाएं, संपत्ति, फलने की स्थितियां", "देखभाल करना — दूसरों, समुदाय और जीवन की"] }
    ]
  },
  staticReflections: {
    seeker: {
      dominant: 'Seeker · Teacher', dominantHi: 'साधक · शिक्षक',
      subtitle: 'The Brahmanic nature — wisdom, inquiry, truth', subtitleHi: 'ब्राह्मणिक प्रकृति — ज्ञान, जिज्ञासा, सत्य',
      reflection: "Your Svadharma is the Seeker and Teacher — what the Gita calls the Brahmanic nature. BG 18.42 names its qualities: shama (tranquility of mind), dama (self-restraint), tapas (austerity), shaucha (purity), kshanti (forgiveness), arjava (straightforwardness), jnana (knowledge), and vijnana — the direct, lived experience of truth.\n\nYour gift to the world is clarity. You are called to understand deeply and illuminate for others. This is not an intellectual project — it is a sacred function. The one who transmits truth across generations, who asks the questions no one else dares to ask, is indispensable to any living civilization.\n\nThe Seeker's greatest temptation is to know without becoming — to hold the map without walking the territory. Your work is to let what you understand change how you actually live. The teacher who has been transformed by what they teach is the only teacher worth having.",
      reflectionHi: "आपका स्वधर्म साधक और शिक्षक है — गीता इसे ब्राह्मणिक प्रकृति कहती है। BG १८.४२ इसके गुण बताता है: शम, दम, तप, शौच, क्षांति, आर्जव, ज्ञान और विज्ञान।\n\nआपका उपहार स्पष्टता है। गहरा समझना और दूसरों को प्रकाशित करना आपका आह्वान है।\n\nसाधक का सबसे बड़ा प्रलोभन है जानना पर बनना नहीं। जो आप समझते हैं वह जीवन को बदले।",
      shloka: 'shamo damas tapah shaucham ksantir arjavam eva ca / jnanam vijnanam astikyam brahma-karma svabhava-jam', shlokaHi: 'शमो दमस्तपः शौचं क्षान्तिरार्जवमेव च / ज्ञानं विज्ञानमास्तिक्यं ब्रह्मकर्म स्वभावजम्',
      shlokaRef: 'BG 18.42',
      shlokaMeaning: 'Tranquility, self-restraint, austerity, purity, forbearance, uprightness, knowledge, wisdom, and faith — these are the duties of the Brahmana born of their own nature.',
      shlokaMeaningHi: 'शम, दम, तप, शौच, क्षांति, आर्जव, ज्ञान, विज्ञान और आस्तिकता — ये ब्राह्मण के स्वभाव से उत्पन्न कर्म हैं।'
    },
    warrior: {
      dominant: 'Warrior · Leader', dominantHi: 'योद्धा · नेता',
      subtitle: 'The Kshatriya nature — courage, duty, protection', subtitleHi: 'क्षत्रिय प्रकृति — साहस, कर्तव्य, रक्षा',
      reflection: "Your Svadharma is the Warrior and Leader — the Kshatriya nature. BG 18.43 names its qualities: shauryam (heroism), tejas (vigour), dhritis (firmness), resourcefulness, not retreating from battle, generosity, and a natural lordliness — the quality of one born to stand in front.\n\nYou are built to lead. Not as performance or ambition, but as dharma — a deep, structural calling. There is a part of you that cannot sit still when injustice is present, when someone needs protecting, or when a situation is leaderless and drifting. That pull is your nature speaking.\n\nThe warrior's shadow is aggression — using strength for domination rather than service. The Gita asks that your power remain in service of dharma. A warrior who fights only for himself is a soldier. A warrior who fights for truth, for the vulnerable, for what is right — that is Arjuna becoming himself.",
      reflectionHi: "आपका स्वधर्म योद्धा और नेता है — क्षत्रिय प्रकृति। BG १८.४३ इसके गुण: शौर्य, तेज, धृति, कार्यकुशलता, युद्ध से न भागना, दान और स्वाभाविक नेतृत्व।\n\nआप नेतृत्व के लिए बने हैं — प्रदर्शन नहीं, धर्म के रूप में। जब अन्याय हो या कोई रक्षाहीन हो, आप रुक नहीं सकते।\n\nयोद्धा की छाया आक्रामकता है। गीता कहती है: शक्ति धर्म की सेवा में रहे।",
      shloka: 'shauryam tejo dhritis dakshyam yuddhe capy apalayanam / danam ishvara-bhavash ca kshatram karma svabhava-jam', shlokaHi: 'शौर्यं तेजो धृतिर्दाक्ष्यं युद्धे चाप्यपलायनम् / दानमीश्वरभावश्च क्षात्रं कर्म स्वभावजम्',
      shlokaRef: 'BG 18.43',
      shlokaMeaning: 'Heroism, vigour, firmness, resourcefulness, not fleeing in battle, generosity, and lordliness — these are the duties of the Kshatriya, born of their nature.',
      shlokaMeaningHi: 'शौर्य, तेज, धृति, दक्षता, युद्ध में न भागना, दान और ईश्वर-भाव — ये क्षत्रिय के स्वभाव से उत्पन्न कर्म हैं।'
    },
    builder: {
      dominant: 'Builder · Creator', dominantHi: 'निर्माता · सृजनकर्ता',
      subtitle: 'The Vaishya nature — prosperity, enterprise, abundance', subtitleHi: 'वैश्य प्रकृति — समृद्धि, उद्यम, प्रचुरता',
      reflection: "Your Svadharma is the Builder and Creator — the Vaishya nature. The Gita names its duties as krishi (agriculture), goraksya (protecting life and ecology), and vanijyam (commerce and enterprise) — the whole material civilizational project. Without the builder's work, wisdom has nowhere to land and warriors have nothing to protect.\n\nYou have a natural gift for seeing resources, recognizing opportunities, and understanding how to connect people, ideas, and energy into things that generate and sustain. This is not a lesser calling — the Gita places it equally among the four. You build the conditions that allow everyone else to flourish.\n\nThe builder's shadow is lobha — when accumulation becomes the end rather than the means. The Gita calls you to practice dana: to let prosperity flow through open hands, to build not only for yourself but for the whole. The true builder creates abundance that multiplies beyond themselves.",
      reflectionHi: "आपका स्वधर्म निर्माता और सृजनकर्ता है — वैश्य प्रकृति। गीता इसके कर्म बताती है: कृषि, गोरक्षा और वाणिज्य — संपूर्ण भौतिक सभ्यता परियोजना।\n\nसंसाधन देखना, अवसर पहचानना, लोगों और विचारों को जोड़ना — यह आपका स्वाभाविक उपहार है।\n\nनिर्माता की छाया लोभ है। गीता कहती है दान करो — समृद्धि खुले हाथों से बहने दो।",
      shloka: 'krishigaurakshyavanijyam vaishya-karma svabhava-jam / paricaryatmakam karma shudrasyapi svabhava-jam', shlokaHi: 'कृषिगौरक्ष्यवाणिज्यं वैश्यकर्म स्वभावजम् / परिचर्यात्मकं कर्म शूद्रस्यापि स्वभावजम्',
      shlokaRef: 'BG 18.44',
      shlokaMeaning: 'Agriculture, cow-protection, and trade are the natural duties of the Vaishya; service is the natural duty of the Shudra.',
      shlokaMeaningHi: 'कृषि, गोरक्षा और वाणिज्य वैश्य के स्वभाव से उत्पन्न कर्म हैं।'
    },
    server: {
      dominant: 'Server · Nurturer', dominantHi: 'सेवक · पोषक',
      subtitle: 'The service nature — care, devotion, sustaining the whole', subtitleHi: 'सेवा प्रकृति — देखभाल, समर्पण, पूर्ण को थामना',
      reflection: "Your Svadharma is the Server and Nurturer — what the Gita calls paricaryatmakam karma: the nature of devoted service. This is among the most undervalued callings in modern life, but the Gita does not rank it as lower. It is different, not lesser. Without those who serve, nothing holds together.\n\nYou find meaning through service — through being genuinely useful, through caring without keeping score. Where others see a task, you see a person. Where others calculate, you simply show up. This is its own kind of intelligence — a relational, attentive, self-transcending intelligence that the world is hungry for.\n\nThe server's shadow is resentment — when care becomes invisible and the server feels unseen, taken for granted, diminished. The Gita's remedy is this: serve as if serving the divine in every being. When service becomes an offering rather than an obligation, it ceases to drain and begins to illuminate. That shift is the whole practice.",
      reflectionHi: "आपका स्वधर्म सेवक और पोषक है — गीता इसे परिचर्यात्मकम् कर्म कहती है: समर्पित सेवा की प्रकृति। यह आधुनिक जीवन में सबसे कम मूल्यांकित आह्वान है, पर गीता इसे कम नहीं मानती।\n\nआप सेवा में अर्थ पाते हैं। जहां दूसरे कार्य देखते हैं, आप व्यक्ति देखते हैं।\n\nसेवक की छाया नाराज़गी है। गीता का उपाय: हर प्राणी में ईश्वर को सेवा करो — यही अभ्यास है।",
      shloka: 'sve sve karmany abhiratah samsiddhim labhate narah / sva-karma-niratah siddhim yatha vindati tac chrinu', shlokaHi: 'स्वे स्वे कर्मण्यभिरतः संसिद्धिं लभते नरः / स्वकर्मनिरतः सिद्धिं यथा विन्दति तच्छृणु',
      shlokaRef: 'BG 18.45',
      shlokaMeaning: 'Each person, devoted to their own duty, attains perfection. Hear now how one devoted to their own work finds that perfection.',
      shlokaMeaningHi: 'अपने-अपने कर्म में लगा हुआ मनुष्य सिद्धि प्राप्त करता है। सुनो कि स्वकर्म में लगा व्यक्ति सिद्धि कैसे प्राप्त करता है।'
    }
  }
};
